FROM ghcr.io/astral-sh/uv:0.9.3-python3.12-trixie-slim

# 设置非交互环境
ENV DEBIAN_FRONTEND=noninteractive

# 指定用户名和用户/组 ID
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG SHELL=/usr/bin/fish
ENV UV_LINK_MODE=copy

# 配置镜像基础环境
RUN <<EOF
    set -euox pipefail
    
    apt-get update
    apt-get install ca-certificates curl git build-essential sudo gpg patchelf ccache python3-dev -y --no-install-recommends 
    
    echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_13/ /' | tee /etc/apt/sources.list.d/shells:fish:release:4.list
    curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:4/Debian_13/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg > /dev/null
    apt-get update && apt-get install fish -y --no-install-recommends
    
    github_url="https://github.com"
    
    architecture="$(dpkg --print-architecture)"
    if [ "${architecture}" != "amd64" ] && [ "${architecture}" != "arm64" ]; then
        echo "(!) Architecture ${architecture} unsupported"
        exit 1
    fi
    version=$(git ls-remote --tags ${github_url}/jgm/pandoc.git | grep -o 'refs/tags/[0-9].*' | sed 's/refs\/tags\///' | sort -V | tail -n1)
    
    curl -Lo pandoc.deb ${github_url}/jgm/pandoc/releases/download/${version}/pandoc-${version}-1-${architecture}.deb
    dpkg -i pandoc.deb && rm pandoc.deb
    
    apt-get clean && rm -rf /var/lib/apt/lists/*
EOF

# 创建用户、加入组、赋予 sudo 权限
RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME && \
    chsh -s $SHELL $USERNAME && \
    chsh -s $SHELL root
